name: 'proyecto_peliculas'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:        
  - "target"
  - "dbt_packages"



tests:
  +store_failures: true
  +database: "ALUMNO6_DEV_SILVER_DB_PR"

models:
  proyecto_peliculas:
    staging:
      +materialized: view
      +intermediate:
        +schema: dbt_gcuesta
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB_PR"
      peliculas_info:
        +schema: dbt_gcuesta   
      api_mas_visto:                         
        +schema: dbt_gcuesta 

    marts:
      + materialized: table
      + database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB_PR"
      + schema: dbt_gcuesta
    
snapshots:
  proyecto_peliculas:
    +target_schema: snapshots
    +materialized: snapshot
    +database: ALUMNO6_DEV_SILVER_DB_PR
    +schema: snapshots
